package com.phoenix.servicecall.models;

import com.google.firebase.Timestamp;

/**
 * Report model — mirrors the Firestore "reports" collection.
 * Generated by Firebase Cloud Functions and stored here for in-app viewing.
 *
 * Types:
 *   "5hr"    — every 5 hours between 8 AM and 10 PM
 *   "daily"  — 10:00 PM full day summary
 *   "weekly" — every Saturday 7:00 PM
 */
public class Report {

    public static final String COLLECTION = "reports";

    public static final String TYPE_5HR    = "5hr";
    public static final String TYPE_DAILY  = "daily";
    public static final String TYPE_WEEKLY = "weekly";

    private String reportId;
    private String type;
    private Timestamp generatedAt;
    private boolean sentToTelegram;
    private int totalTasks;
    private int completedCount;
    private int pendingCount;
    private String aiSummary;
    private String rawContent;   // full formatted report text

    public Report() {}

    // Getters & Setters
    public String getReportId() { return reportId; }
    public void setReportId(String id) { this.reportId = id; }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    public Timestamp getGeneratedAt() { return generatedAt; }
    public void setGeneratedAt(Timestamp ts) { this.generatedAt = ts; }

    public boolean isSentToTelegram() { return sentToTelegram; }
    public void setSentToTelegram(boolean sent) { this.sentToTelegram = sent; }

    public int getTotalTasks() { return totalTasks; }
    public void setTotalTasks(int total) { this.totalTasks = total; }

    public int getCompletedCount() { return completedCount; }
    public void setCompletedCount(int count) { this.completedCount = count; }

    public int getPendingCount() { return pendingCount; }
    public void setPendingCount(int count) { this.pendingCount = count; }

    public String getAiSummary() { return aiSummary; }
    public void setAiSummary(String summary) { this.aiSummary = summary; }

    public String getRawContent() { return rawContent; }
    public void setRawContent(String content) { this.rawContent = content; }
}
